# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: RPSLS testing pipe

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.0"
        
    - name: Create environment
      run: |
        pip install virtualenv
        python -m venv .venv
        source .venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit test
      run: |
        python ./run_tests.py

    - name: Generate Cov
      run: |
        coverage run -m unittest discover -s tests
        coverage html
        
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: unit test result
        path: ./tests/test-reports
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./tests/htmlcov
